# Generated by Django 4.0.4 on 2022-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='source',
            field=models.CharField(default='dummy', max_length=30, verbose_name='紹介方法'),
            preserve_default=False,
        ),
    ]
