# Generated by Django 4.0.4 on 2022-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='source',
            field=models.CharField(blank=True, max_length=30, verbose_name='紹介方法'),
        ),
    ]
