# Generated by Django 4.0.4 on 2022-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='count_bad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answeruser',
            name='count_commented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answeruser',
            name='count_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionuser',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
