# Generated by Django 4.0.3 on 2022-07-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruserprofile',
            name='answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answeruserprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answeruserprofile',
            name='questions',
            field=models.IntegerField(default=0),
        ),
    ]
