# Generated by Django 4.0.3 on 2022-04-15 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
