# Generated by Django 4.0.4 on 2022-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruserprofile',
            name='nickname',
            field=models.CharField(default='dummy', max_length=30, verbose_name='ペンネーム'),
            preserve_default=False,
        ),
    ]
