# Generated by Django 4.0.4 on 2022-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0002_answeruserprofile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='登録用コード')),
                ('purpose', models.CharField(max_length=30, verbose_name='使用目的')),
                ('source', models.CharField(max_length=30, verbose_name='紹介方法')),
            ],
        ),
    ]
