# Generated by Django 4.0.3 on 2022-04-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0002_topic_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='匿名', max_length=100, verbose_name='投稿者の名前'),
        ),
    ]
