# Generated by Django 4.0.4 on 2022-06-19 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0002_answeruser_count_bad_answeruser_count_commented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionuser',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
