# Generated by Django 4.0.3 on 2022-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0002_answeruserprofile_answers_answeruserprofile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
