# Generated by Django 4.0.3 on 2022-04-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0003_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
