# Generated by Django 4.0.4 on 2022-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0004_alter_validationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationcode',
            name='code',
            field=models.CharField(max_length=30, verbose_name='登録用コード'),
        ),
    ]
