# Generated by Django 4.0.3 on 2022-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0004_remove_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='匿名', max_length=100, verbose_name='投稿者の名前'),
        ),
    ]
