# Generated by Django 4.0.3 on 2022-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0005_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='file/document_list/document/', verbose_name='ファイル')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='file/photo_list/photo/', verbose_name='フォト')),
            ],
        ),
    ]
