# Generated by Django 4.0.3 on 2022-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0006_documentlist_photolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='genre',
            field=models.CharField(default='一時的', max_length=20, verbose_name='質問のジャンル'),
            preserve_default=False,
        ),
    ]
