# Generated by Django 4.0.3 on 2022-04-21 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0007_topic_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='匿名', max_length=100, verbose_name='投稿者の名前')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('genre', models.CharField(max_length=20, verbose_name='質問のジャンル')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_QA.topic', verbose_name='対象トピック')),
            ],
        ),
    ]
