# Generated by Django 4.0.3 on 2022-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_QA', '0008_topicreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicreply',
            name='genre',
        ),
    ]
